packages:
  - client
  - admin
  - server
  - packages/*

# client/server 각각의 pnpm-workspace.yaml에서 통합한 설정
allowBuilds:
  bcrypt: true
  core-js: false
  cpu-features: false
  esbuild: true
  protobufjs: true
  ssh2: false
  unrs-resolver: true
